version: "3.9"
services:
  mailer-container:
    image: mailer-image
    container_name: mailer-container
    environment:
      - SMTP_DOMAIN=localhost:1025
      - SMTP_HOST=localhost
      - SMTP_USERNAME=smtp
      - SMTP_PASSWORD=password
      - SMTP_FROM=from@mailer
      - SMTP_FROM_PASSWORD=password
      - SMTP_FROM_NAME=from
      - MONGODB_HOST=mongodb-mailer-image
      - MONGODB_USERNAME=mailer
      - MONGODB_PASSWORD=password
      - MONGODB_DB_NAME=mailer
      - MONGODB_PORT=27017
    restart: always
    ports:
      - "8080:8080"