version: "3.9"
services:
  mailer-container:
    image: mailer-image
    container_name: mailer-container
    environment:
      - REDIS_HOST=redis-mailer:6379
      - REDIS_PASSWORD=password
      - REDIS_DB=0
      - SMTP_DOMAIN=localhost:1025
      - SMTP_HOST=localhost
      - SMTP_USERNAME=smtp
      - SMTP_PASSWORD=password
      - SMTP_FROM=from@mailer
      - SMTP_FROM_PASSWORD=password
      - SMTP_FROM_NAME=from
    restart: always
    ports:
      - "8080:80"