version: "3.9"
services:
  mongodb-mailer-container:
    network_mode: host
    container_name: mongodb-mailer-container
    image: mongodb-mailer-image
    environment:
        - MONGO_USERNAME=admin
        - MONGO_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local